#!/usr/bin/python3
import os

import pytest

from app import nussinov
from defs import ROOT_DIR


def test_simple_strand():
    test_strand = 'gGGACCUUCCCGGUCUC'.upper()

    base_pairs = nussinov.nussinov_algorithm(test_strand)

    assert (0, 16) == base_pairs[0]

def test_long_strand():
    test_strand = 'GuGUGCCCGGCAUGGGUGCAGUCUAUAGGGUGAGAGUCCCGAACUGUGAAGGCAGAAGUA\
ACAGUUAGCCUAACGCAAGGGUGUCCGUGGCGACAUGGAAUCUGAAGGAAGCGGACGGCA\
AACCUUCGGUCUGAGGAACACGAACUUCAUAUGAGGCUAGGUAUCAAUGGAUGAGUUUGC\
AUAACAAAACAAAGUCCUUUCUGCCAAAGUUGGUACAGAGUAAAUGAAGCAGAUUGAUGA\
AGGGAAAGACUGCAUUCUUACCCGGGGAGGUCUGGAAACAGAAGUCAGCAGAAGUCAUAG\
UACCCUGUUCGCAGGGGAAGGACGGAACAAGUAUGGCGUUCGCGCCUAAGCUUGAACCGC\
CGUAUACCGAACGGUACGUACGGUGGUGUGAGAGGAGUUCGCUCUACUCUAUuGUUAUUUU'.upper()

    base_pairs = nussinov.nussinov_algorithm(test_strand)

    desired_pairs = 175

    assert desired_pairs == len(base_pairs)
