#!/usr/bin/python3
from app import nussinov


def test_simple_strand():
    test_strand = 'gGGACCUUCCCGGUCUC'.upper()

    base_pair = nussinov.nussinov_algorithm(test_strand)[0]

    assert (1, 17) == (base_pair[0].position, base_pair[1].position)

def test_long_strand():
    test_strand = 'GuGUGCCCGGCAUGGGUGCAGUCUAUAGGGUGAGAGUCCCGAACUGUGAAGGCAGAAGUA\
ACAGUUAGCCUAACGCAAGGGUGUCCGUGGCGACAUGGAAUCUGAAGGAAGCGGACGGCA\
AACCUUCGGUCUGAGGAACACGAACUUCAUAUGAGGCUAGGUAUCAAUGGAUGAGUUUGC\
AUAACAAAACAAAGUCCUUUCUGCCAAAGUUGGUACAGAGUAAAUGAAGCAGAUUGAUGA\
AGGGAAAGACUGCAUUCUUACCCGGGGAGGUCUGGAAACAGAAGUCAGCAGAAGUCAUAG\
UACCCUGUUCGCAGGGGAAGGACGGAACAAGUAUGGCGUUCGCGCCUAAGCUUGAACCGC\
CGUAUACCGAACGGUACGUACGGUGGUGUGAGAGGAGUUCGCUCUACUCUAUuGUUAUUUU'.upper()

    base_pairs = nussinov.nussinov_algorithm(test_strand)

    desired_pairs = 175

    assert desired_pairs == len(base_pairs)
